org.gradle.jvmargs=-Xmx2G

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14
fabric_version=0.133.4+1.21.8

mod_version=1.0.0
maven_group=io.github.Launchpad_Tristan
archives_base_name=for_the_greater_god

org.gradle.java.installations.paths=C:\Program Files\Microsoft\jdk-21.0.12.8-hotspot\bin\java.exe